name: sc
channels:
  - conda-forge
dependencies:
  - python=3.10
  - huggingface_hub
  - datasets
  - certifi
  - fsspec=2023.9.2
  - jupyterlab
  - ipywidgets
  - matplotlib
  - seaborn
  - accelerate
  - bitsandbytes
  - ca-certificates
  - openssl
  - nltk
  - pip:
      - vllm
